name: live_app
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.0.2 <4.0.0"

dependencies:

  bouncing_draggable_dialog: ^1.0.2
  clipboard: ^0.1.3
  contained_tab_bar_view: ^0.8.0
  country_code_picker: ^3.0.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  flutter_animated_dialog: ^2.0.1
  flutter_otp_text_field: ^1.1.1
  flutter_screenutil: ^5.8.4
  get: ^4.6.5
  google_fonts: ^5.0.0
  google_nav_bar: ^5.0.6
  shared_preferences: ^2.2.0
  provider: ^6.0.5
  image_picker: ^1.0.2
  http: ^1.1.0
  connectivity: ^3.0.6
  fluttertoast: ^8.2.2
  intl: ^0.18.1
  shimmer: ^3.0.0
  like_button: ^2.0.5
  photo_view: ^0.14.0
  dio: ^5.3.2
  image_cropper: ^5.0.0
  zego_express_engine: ^3.8.1
  permission_handler: 8.1.2
  marquee_text: ^2.5.0+1

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/decoration/
    - assets/icons/
    - assets/dummy/
    - assets/room_icons/
    - assets/treas/
    - assets/gifts/
    - assets/emoji/
    - assets/agency/
    - assets/svip_benefits_ic/
